name: ADF CI/CD Pipeline (adf_publish trigger)

on:
  push:
    branches:
      - adf_publish

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout adf_publish branch
        uses: actions/checkout@v4
        with:
          ref: adf_publish

      - name: Install/Update Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az upgrade --yes

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to PROD ADF
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: RG-Fingrid-Prod
          dataFactoryName: Fingrid-Prod
          armTemplateFile: ./Fingrid-test-001/ARMTemplateForFactory.json
          armTemplateParametersFile: ./Fingrid-test-001/ARMTemplateParametersForFactory.json
          additionalParameters: |
            -factoryName Fingrid-Prod
            -keyvault_prod_linkedService_properties_typeProperties_baseUrl "https://prod-keyvault.vault.azure.net/"
